### ISSUE TITLE
3.0.4 causing lag

### ISSUE THREAD

**Issue by SikaObi** [aRTy42/POE-ItemInfo#104] opened 2017-10-18 08:44 UTC
After updating from 3.0.3, my fps plummeted from about 100 to 30 in hideout, and even worse in maps. Also observed the game crashing on me more frequently. Tried the usual reboot, fresh install solutions, but reverted back to 3.0.3 which causes no issues for me.

**Comment by Eruyome** [comment] 2017-10-18 10:24
Are you using the new tooltip (GDI+, colored) or the default one?

**Comment by Eruyome** [comment] 2017-10-18 14:39
Please tell me if this is related to having the new optional GDI tooltip enabled.
If not, disable GDI, edit `<ItemInfo/TradeMacro Folder>\resources\ahk\PoE-ItemInfo.ahk` and remove this line

```
global gdipTooltip = new GdipTooltip(2, 8,,,[Opts.GDIWindowOpacity, Opts.GDIWindowColor, 10],[Opts.GDIBorderOpacity, Opts.GDIBorderColor, 10],[Opts.GDITextOpacity, Opts.GDITextColor, 10],true, Opts.RenderingFix, -0.3)
```

then try again.

**Comment by Tiolius** [comment] 2017-10-18 20:02
Same problem here.
GDI+ not enabled in options.
I try delete line global gdipTooltip = new GdipTooltip...... this fix fps drop after start macro, but fps still drop after any macro hotkey usage, Ctrl+D or Ctrl+C for example and while macro tooltip on screen. After tooltip fades away, fps restoring to normal.

**Comment by aRTy42** [comment] 2017-10-18 20:32
The FPS drop once the game is no longer the main window (while a tooltip is up) is common behaviour, it is the same with all other windows or when you tab out. We'll need to see what we can do about the general drop once GDI is involved.

**Comment by SikaObi** [comment] 2017-10-18 20:46
Alright, I removed the code line, and everything seems to be back to normal. I was and am using the default tooltip, no colors or anything. Also, I have to point out the fps drop was constant, not only when the tooltip was up.

**Comment by Eruyome** [comment] 2017-10-19 07:18
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/beta.zip
Can you try this dev version? It prevents the gdi+ tooltip class being initialised (basically removing the line that I showed you) when the tooltip is disabled on scriptstart.
While this isn't a real fix it should enable users to run the macro as usual.

**Comment by SikaObi** [comment] 2017-10-19 13:44
I'm having no issues with this version

**Comment by Eruyome** [comment] 2017-10-19 18:49
Can you guys tell me what graphics card you have, if your drivers are up to date, whether you're using VSync, either globally for all games via graphics card settings or via PoE game settings?

**Comment by Tiolius** [comment] 2017-10-19 20:02
This beta build work fine for me.
I have Nvidia GeForce GTX 660 with latest drivers installed.
VSync disabled in PoE and i not use global settings for games.

**Comment by aRTy42** [comment] 2017-10-19 21:36
Both TradeMacro and ItemInfo have a new beta-release now where this change is included.

**Comment by Zeerimunin** [comment] 2017-10-20 17:42
Posted in the Reddit thread as well, but the issue is gone with the new beta.  I'm running a GTX1080, driver ver 382.05.  Vsync is disabled everywhere both on desktop and in game options.

**Comment by aRTy42** [comment] 2017-10-31 00:12
Since the permanent FPS drop issue is resolved and we can probably not fix the impact of GDI+ if people choose to use it, I'll close this issue.

**Closed as completed by aRTy42** 2017-10-31 00:12 UTC
